import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('../..');
const password=process.env.SEED_PASSWORD??fs.readFileSync(path.join(root,'.env'),'utf8').split(/\r?\n/).find(l=>l.startsWith('SEED_PASSWORD='))!.slice(14);
test('Korean workspace, upload, review gate and valid editable artifact',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'연금술사',exact:true})).toBeVisible();
  await page.screenshot({path:path.join(root,'test-results/login.png'),fullPage:true});
  await page.getByLabel('계정',{exact:true}).fill('demo-user');
  await page.getByLabel('비밀번호',{exact:true}).fill(password);
  await page.getByRole('button',{name:'로그인 →'}).click();
  await expect(page.getByLabel('프로젝트 선택')).toBeVisible();
  test.skip(await page.getByText('프로토타입-검토패스 · 검토자 승인 없이',{exact:false}).isVisible(),'Strict review scenario; run with PROTOTYPE_REVIEW_MODE=strict');
  await page.getByLabel('프로젝트 선택').selectOption({label:'합성 데이터 검증 프로젝트 1'});
  await page.getByLabel('문서 업로드').setInputFiles(path.join(root,'tests/golden/fixtures/synthetic.docx'));
  const document=page.getByRole('button').filter({hasText:'synthetic.docx'}).last();
  await expect(document).toContainText('보안검사 완료',{timeout:45000});
  await document.click();
  await page.getByRole('button',{name:'분석 시작',exact:true}).click();
  await expect(page.getByRole('button',{name:'계획 보기'}).first()).toBeVisible({timeout:60000});
  await page.getByRole('button',{name:'계획 보기'}).first().click();
  await expect(page.getByRole('button',{name:'PPTX 생성',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:/원문 근거/}).first().click();
  await expect(page.getByRole('dialog',{name:'원문 근거'})).toContainText('합성');
  await page.getByRole('button',{name:'닫기 ×'}).click();
  await page.screenshot({path:path.join(root,'test-results/workspace.png'),fullPage:true});
  await page.getByTitle('로그아웃').click();
  await page.getByLabel('계정',{exact:true}).fill('demo-reviewer');
  await page.getByLabel('비밀번호',{exact:true}).fill(password);
  await page.getByRole('button',{name:'로그인 →'}).click();
  await expect(page.getByLabel('프로젝트 선택')).toBeVisible();
  test.skip(await page.getByText('프로토타입-검토패스 · 검토자 승인 없이',{exact:false}).isVisible(),'Strict review scenario; run with PROTOTYPE_REVIEW_MODE=strict');
  await page.getByLabel('프로젝트 선택').selectOption({label:'합성 데이터 검증 프로젝트 1'});
  await page.getByRole('button').filter({hasText:'synthetic.docx'}).last().click();
  await page.getByRole('button',{name:'계획 승인',exact:true}).click();
  await expect(page.getByRole('button',{name:'PPTX 생성',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'PPTX 생성',exact:true}).click();
  await expect(page.getByText(/QA PASS/).first()).toBeVisible({timeout:60000});
  const downloadEvent=page.waitForEvent('download');
  await page.getByRole('button',{name:'다운로드 ↓'}).first().click();
  const download=await downloadEvent;expect(download.suggestedFilename()).toMatch(/\.pptx$/);
  await page.screenshot({path:path.join(root,'test-results/artifact-review.png'),fullPage:true});
  expect(errors).toEqual([]);
});
