import {useEffect,useState} from 'react';
import {api,stateLabel} from './api';
import type {Project,Job} from './types';
type Theme={id:string;name:string;config:{background:string;foreground:string;accent:string;source:string;reference_slides?:number;reference_fonts?:Record<string,number>;license?:string;source_url?:string}};
export function DesignLibrary({project,owner,onSave}:{project:Project|null;owner:boolean;onSave:(p:Project)=>void}){
 const [themes,setThemes]=useState<Theme[]>([]),[jobs,setJobs]=useState<Job[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){const result=await api<{themes:Theme[]}>('/design-library');setThemes(result.themes);if(project){const all=await api<Job[]>(`/projects/${project.id}/jobs`);setJobs(all.filter(j=>j.kind==='design_reference'));}}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));const timer=setInterval(()=>void refresh().catch(e=>setError(e.message)),3000);return()=>clearInterval(timer);},[project?.id]);
 async function select(id:string|null){if(!project)return;setBusy(true);setError('');try{onSave(await api<Project>(`/projects/${project.id}`,{method:'PATCH',body:JSON.stringify({name:project.name,description:project.description,security_class:project.security_class,template_id:id})}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <><section className="panel design-intro"><span className="eyebrow">DESIGN LIBRARY</span><h2>발표자료의 디자인을 모아두세요.</h2><p>참고 PPT에서 색상·글꼴 크기·배치 특징을 추출해 조직의 디자인으로 저장합니다. 다음 문서 분석에 저장한 스타일을 참고합니다.</p><p className="hint">모델 가중치를 재학습하는 기능은 아닙니다. 참고 PPT의 본문·사진·로고를 새 문서에 복사하지 않으며, 글꼴은 설치된 한국어 폰트로 맞춥니다.</p><label className="dropzone"><strong>{busy?'처리 중…':'참고 PPTX 여러 개 업로드'}</strong><small>{project?'격리 → 검증 → 악성코드 검사 → 스타일 추출 → 저장':'상단에서 프로젝트를 먼저 선택하세요.'}</small><input aria-label="참고 PPT 업로드" type="file" multiple accept=".pptx" disabled={!project||busy} onChange={e=>{const files=Array.from(e.target.files??[]);e.target.value='';if(!project)return;void(async()=>{setBusy(true);setError('');try{for(const file of files){const form=new FormData();form.append('file',file);await api(`/projects/${project.id}/design-references`,{method:'POST',body:form});}await refresh();}catch(err){setError(String(err));}finally{setBusy(false);}})();}}/></label>{error&&<p role="alert" className="error">{error}</p>}{jobs.slice(0,5).map(j=><div className="job" key={j.id}><span>스타일 추출 · {stateLabel[j.state]??j.state} · {j.step}{j.error_code&&` · ${j.error_code}`}</span><progress value={j.progress} max={100}/><span>{j.progress}%</span></div>)}</section>
 <div className="section-title"><h2>저장된 디자인 <small>{themes.length}종</small></h2><button disabled={!project||!owner||busy} onClick={()=>void select(null)}>내용에 맞게 자동 선택</button></div><p className="hint">선택한 테마는 다음 ‘분석 시작’부터 적용됩니다. 이미 생성한 계획과 산출물의 디자인은 유지됩니다. 자동 선택은 내용 태그와 조직의 업로드 이력을 참고합니다.</p><div className="theme-grid">{themes.map(t=><article className="theme-card" key={t.id}><div className="theme-preview" style={{background:'#'+t.config.background,color:'#'+t.config.foreground}}><span style={{color:'#'+t.config.accent}}>DOCUMENT / PRESENTATION</span><strong>핵심을 명확하게.<br/>근거를 설득력 있게.</strong><div style={{background:'#'+t.config.accent}}/><small>01 ━━━━━━━━━━━</small></div><div className="theme-description"><h3>{t.name}</h3><p>{t.config.source==='uploaded-reference'?`우리 조직 · ${t.config.reference_slides}장 스타일 추출`:'기본 제공 · '+(t.config.license??'프로젝트 기본 테마')}</p>{t.config.reference_fonts&&<small>참고 글꼴: {Object.keys(t.config.reference_fonts).join(', ')||'테마 기본값'}</small>}<button className={project?.template_id===t.id?'primary':''} disabled={!project||!owner||busy} onClick={()=>void select(t.id)}>{project?.template_id===t.id?'사용 중':'이 디자인 사용'}</button></div></article>)}</div></>;
}
