export interface Me {id:string;username:string;role:string;org_id:string;modes:Record<string,string>;environment:string}
export interface Project {id:string;name:string;description:string;security_class:string;owner_id:string}
export interface Document {id:string;title:string;current_version_id:string|null}
export interface Evidence {document_version_id:string;chunk_id:string;section:string;page:number|null;node_ids:string[]}
export interface Block {type:string;text:string;cells:string[][];source_refs:Evidence[]}
export interface Slide {slide_id:string;version:number;order:number;title:string;layout_type:string;content_blocks:Block[];source_refs:Evidence[];visual_plan:{mode:string;workflow:string;controlnet:string|null;ip_adapter:boolean;seed:number;prompt:string}}
export interface PlanData {schema_version:string;plan_id:string;title:string;document_versions:string[];audience:string;slides:Slide[];mock:boolean;provenance:Record<string,unknown>}
export interface Plan {id:string;version:number;status:string;approved_version:number|null;data:PlanData}
export interface Job {id:string;job_id:string;kind:string;state:string;step:string;progress:number;seq:number;error_code:string|null;result:Record<string,string>;steps:{step:string;state:string;attempts:number}[]}
export interface Version {id:string;version:number;approval_status:string;qa_status:string;official_eligible:boolean;sha256:string;qa_report:Record<string,unknown>;provenance:{slides:Slide[];mock:boolean;plan_version:number}}
export interface Artifact {id:string;type:string;current_version:Version;versions?:Version[]}
export interface Chunk {chunk_id:string;text:string;section_id:string;source_location:Record<string,unknown>}
